//
//  PurchaseListModels.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 10/28/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct PurchaseList{
    
    struct FetchItems {
        struct Request{
        }
        
        struct Response{
            var items: [Item]
        }
        
        struct ViewModel{
            struct DisplayedItem{
                var name: String?
                var quantity: String?
            }
            var displayedItems: [DisplayedItem]
        }
    }
    
    
    struct Delete {
        struct Request{
            var index = 0
        }
        
        struct Response{
            var index = 0
            var successfully: Bool
        }
        
        struct ViewModel{
            struct Error {
                var alertController: UIAlertController
            }
            struct Successful {
                var indexPath: IndexPath
            }
        }
    }
    
}

