//
//  PurchaseListWorker.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 10/28/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class PurchaseListWorker{
    // MARK: Business Logic
    
    func doSomeWork(){
        // NOTE: Do the work
    }
}
