//
//  AddItemWorker.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 11/3/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class AddItemWorker{
    // MARK: Business Logic
    
    func checkNilsInBothStrings(name: String?, quantity: String?) -> Bool{
        if (checkEmptyOrHasWhiteSpaces(string: name) || checkEmptyOrHasWhiteSpaces(string: quantity)) {
            return true
        }
        return false
    }
    
    
    
    func checkEmptyOrHasWhiteSpaces(string: String?) -> Bool {
        guard string != nil else {
            return true
        }
        let stringWithoutSpaces = string!.trimmingCharacters(in: NSCharacterSet.whitespacesAndNewlines)
        if(stringWithoutSpaces.isEmpty) {
            return true
        }
        return false
    }
    

    func isNumber(number: String?) -> Bool{
        guard number != nil else {
            return false
        }
        let inverseSet = NSCharacterSet(charactersIn:"0123456789").inverted
        let components = number!.components(separatedBy: inverseSet)
        let filtered = components.joined(separator: "")
        return number == filtered
    }
    
    
    func createResponse(name: String?, quantity: String?) -> (AddItem.Insert.Response, Item?){
        let parametersHaveNils = checkNilsInBothStrings(name: name, quantity: quantity)
        if parametersHaveNils{
            return (AddItem.Insert.Response(result: .OneOrMoreParametersAreNil),nil)
        }
        if isNumber(number: quantity){
            return (AddItem.Insert.Response(result: .NoErrors), Item(name: name, quantity:NSNumber(value:Int(quantity!)!), id: nil))
        }
        return (AddItem.Insert.Response(result: .QuantityIsnAValidNumber),nil)
    }
    
}
