//
//  AddItemModels.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 11/2/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

enum AddItemResult {
    case OneOrMoreParametersAreNil
    case QuantityIsnAValidNumber
    case NoErrors
    case ErrorSavingItem
}


struct AddItem{
    
    struct Insert {
        struct Request{
            var name: String?
            var quantity: String?
        }
        struct Response{
            var result: AddItemResult
        }
        
        struct ViewModel{
            var alert: UIAlertController
        }
    }
}

