//
//  AddItemViewController.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 11/2/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AddItemViewControllerInput{
    func displaySomething(viewModel: AddItem.ViewModel)
}

protocol AddItemViewControllerOutput{
    func doSomething(request: AddItem.Request)
}

class AddItemViewController: UIViewController, AddItemViewControllerInput{
    var output: AddItemViewControllerOutput!
    var router: AddItemRouter!
    
    
    // MARK: OUTLETS
    @IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var quantityTextField: UITextField!
    
    
    // MARK: Object lifecycle
    
    override func awakeFromNib(){
        super.awakeFromNib()
        AddItemConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad(){
        super.viewDidLoad()
        title = "Add Item"
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad(){
        // NOTE: Ask the Interactor to do some work
        
        let request = AddItem.Request()
        output.doSomething(request: request)
    }
    
    // MARK: Display logic
    
    func displaySomething(viewModel: AddItem.ViewModel){
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}
