//
//  AddItemInteractor.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 11/2/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AddItemInteractorInput{
    func doSomething(request: AddItem.Request)
}

protocol AddItemInteractorOutput{
    func presentSomething(response: AddItem.Response)
}

class AddItemInteractor: AddItemInteractorInput{
    var output: AddItemInteractorOutput!
    var worker: AddItemWorker!
    
    // MARK: Business logic
    
    func doSomething(request: AddItem.Request){
        // NOTE: Create some Worker to do the work
        
        worker = AddItemWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        
        let response = AddItem.Response()
        output.presentSomething(response: response)
    }
}
