//
//  AddItemPresenter.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 11/2/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AddItemPresenterInput{
    func presentSomething(response: AddItem.Response)
}

protocol AddItemPresenterOutput: class{
    func displaySomething(viewModel: AddItem.ViewModel)
}

class AddItemPresenter: AddItemPresenterInput{
    weak var output: AddItemPresenterOutput!
    
    // MARK: Presentation logic
    
    func presentSomething(response: AddItem.Response){
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        
        let viewModel = AddItem.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
