//
//  AddItemConfigurator.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 11/2/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension AddItemViewController: AddItemPresenterOutput{
    func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?){
        router.passDataToNextScene(segue: segue)
    }
}

extension AddItemInteractor: AddItemViewControllerOutput{
}

extension AddItemPresenter: AddItemInteractorOutput{
}

class AddItemConfigurator{
    // MARK: Object lifecycle
    
    class var sharedInstance: AddItemConfigurator{
        struct Static {
            static let instance =  AddItemConfigurator()
        }
        return Static.instance
    }
    
    // MARK: Configuration
    
    func configure(viewController: AddItemViewController){
        let router = AddItemRouter()
        router.viewController = viewController
        
        let presenter = AddItemPresenter()
        presenter.output = viewController
        
        let interactor = AddItemInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
