//
//  AddItemWorkerTests.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 11/3/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import PurchaseList
import XCTest

class AddItemWorkerTests: XCTestCase{
    // MARK: Subject under test
    
    var sut: AddItemWorker!
    
    // MARK: Test lifecycle
    
    override func setUp(){
        super.setUp()
        setupAddItemWorker()
    }
    
    override func tearDown(){
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupAddItemWorker(){
        sut = AddItemWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testNilStrings(){
        XCTAssert(sut.checkNilsInBothStrings(name: nil, quantity: nil))
    }
    
    func testEmptySpaces(){
        XCTAssert(sut.checkEmptyOrHasWhiteSpaces(string: ""))
        XCTAssert(sut.checkEmptyOrHasWhiteSpaces(string: ""))
        XCTAssertFalse(sut.checkEmptyOrHasWhiteSpaces(string: "test "))
    }
    
    func testIsNumber(){
        XCTAssert(sut.isNumber(number: "12345"))
        XCTAssertFalse(sut.isNumber(number: "test"))
    }
    
}
