//
//  AddItemPresenterTests.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 11/3/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import PurchaseList
import XCTest

class AddItemPresenterTests: XCTestCase{
    // MARK: Subject under test
    
    var sut: AddItemPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp(){
        super.setUp()
        setupAddItemPresenter()
    }
    
    override func tearDown(){
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupAddItemPresenter(){
        sut = AddItemPresenter()
    }
    
   
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testSomething(){
        // Given
        
        // When
        
        // Then
    }
}
