//
//  AddItemViewControllerTests.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 11/3/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import PurchaseList
import XCTest

class AddItemViewControllerTests: XCTestCase{
    // MARK: Subject under test
    
    var sut: AddItemViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp(){
        super.setUp()
        window = UIWindow()
        setupAddItemViewController()
    }
    
    override func tearDown(){
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupAddItemViewController(){
        let storyboard = UIStoryboard(name: "Main", bundle: Bundle(for: type(of: self)))
        sut = storyboard.instantiateViewController(withIdentifier: "AddItemViewController") as! AddItemViewController
    }
    
    func loadView(){
        window.addSubview(sut.view)
        RunLoop.current.run(until: NSDate() as Date)
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    class AddItemViewControllerOutputSpy: AddItemViewControllerOutput{
        // MARK: Method call expectations
        var insertItemCalled = false
        
        // MARK: Spied methods
        func insertItem(request: AddItem.Insert.Request){
            insertItemCalled = true
        }
    }
    
    
    // MARK: Tests
    func testInsertMethodWhenItemButtonIsPressed(){
        // Given
        let addItemViewControllerOutputSpy = AddItemViewControllerOutputSpy()
        sut.output = addItemViewControllerOutputSpy
        // When
        let request = AddItem.Insert.Request()
        sut.output.insertItem(request: request)
        // Then
        
        XCTAssert(addItemViewControllerOutputSpy.insertItemCalled)
    }
    
}
