//
//  PurchaseListWorkerTests.swift
//  PurchaseList
//
//  Created by Cesar Brenes on 10/28/16.
//  Copyright (c) 2016 Cesar Brenes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import PurchaseList
import XCTest

class PurchaseListWorkerTests: XCTestCase{
    // MARK: Subject under test
    
    var sut: PurchaseListWorker!
    
    // MARK: Test lifecycle
    
    override func setUp(){
        super.setUp()
        setupPurchaseListWorker()
    }
    
    override func tearDown(){
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPurchaseListWorker(){
        sut = PurchaseListWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testSomething(){
        // Given
        
        // When
        
        // Then
    }
}
